favicon:
  href: /blog/favicon.png # Favicon of your site.
  type: image/png # Icon type, possible values are(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

search: https://ecosia.org/search?q= # https://www.google.com/search?q==
order_by: date # date,-date,title,url,...
head: '<!--<script src="" async></script>-->' # Add anything to <head></head>

archives:
  switch: false # true,false Switching this function.
  categories: [] # Only the categories you set will be displayed on the archive page.

menu:
  Archives: archives
  About: about.html

footer_link:
  Yet the Books: https://github.com/Yet-The-Books/hexo-theme-yet-the-books
  My Blog: https://aspiring-writer.github.io

github:
  repo: # Aspiring-Writer/hexo-theme-library
  edit: true # true,false
  history: true # true,false

analytics: # Statistics system, currently supports Google analytics.js statistics, Google Tag Manager statistics, CNZZ statistics, Tencent statistics, 51.La statistics, Baidu statistics
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: #<ID>
  gtm_container_id: #<ID>

cdn: # Here you can modify the CDN of the library used by the site
  disqusjs:
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    css: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.css
    js: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine

comment: utteranc # Comment box, currently supports gitalk, gitment, valine, disqus, disqusjs, changyan, livere, DiscussBot, utteranc, giscus Use false to close

gitalk:
  admin: # Has the GitHub username to operate on this repo
  owner: # The GitHub username that holds the repo
  repo: # The repo where the issue where comments are stored
  clientID: # GitHub Client ID
  clientSecret: # GitHub Client Secret

gitment:
  owner: # The GitHub username that holds the repo
  repo: # The repo where the issue where comments are stored
  clientID: # GitHub Client ID
  clientSecret: # GitHub Client Secret

valine: 
  appId: <API_ID> # leancloud application app id
  appKey: <API_Key> # leancloud application app key

disqus:
  shortname: <shortname> # 你的 Disqus shortname

disqusjs:
  shortname: <shortname> # 你的 Disqus shortname
  sitename: <sitename> # The name of your site, which will be displayed in the "Comment Basic Mode" header; this configuration should be consistent with Disqus Admin - Settings - General - Website Name
  api: https://disqus.skk.moe/disqus/ # API Endpoint requested by DisqusJS, usually you should configure a Disqus API reverse generation and fill in the reverse generation address. You can also directly use the Endpoint of DISQUS official API https://disqus.com/api/, or use the Disqus API built by SukkaW to reverse the Endpoint https://disqus.skk.moe/disqus/.
  apikey: <api_key> # The API Key used by DisqusJS to initiate a request to the API. You should obtain the API Key when configuring the Disqus Application; DisqusJS supports filling in an Array containing multiple API Keys, which will be randomly used in each request One of them; if you only need to fill in one API Key, you can fill in String or Array.
  admin: <admin> # The username of the Disqus Moderator for your site (that is, your username). You can get your Username in Disqus - Settings - Account - Username
  adminLabel: <adminLabel> # The text you want to display in the Disqus Moderator Badge. The configuration should be the same as Disqus Admin - Settings - Community - Moderator Badge Text

changyan:
  appid: <APP_ID> # Changyan's APPID
  conf: <CONF> # Talking CONF
  thread_key_type: path # optional id or path

deliver:
  data_uid: <data_uid> # Your Laibili UID, you can get it in Lapili background

DiscussBot:
  id: <id> # site id
  comments: 5 # Maybe limit the maximum number of comments per user per page?
  color: # The main color of the comment box
  dislike: 0 # show the dislike button
  icons: 0 # icon theme
  diff: 0 # different color for each user name

utteranc: # https://utteranc.es/
  repo: [ENTER REPO HERE]
	issue_term: pathname
	label: Comment
	theme: github-light

giscus: # https://giscus.app/
  repo: [ENTER REPO HERE]
  repo_id: 
  category: General
  category_id:
  mapping: title
  reactions_enabled: true
  theme: light
  lang: zh-CN